# ZINC

The ZINC dataset is a collection of molecular graphs used for predicting molecular properties. It contains about 250,000 commercially available organic molecules with up to 38 heavy atoms (C, N, O, S, F). Each molecule is represented as a graph where atoms are nodes and chemical bonds are edges. The task associated with this dataset is typically to predict a quantum mechanical property of the molecule - specifically, the constrained solubility.

From TUDataset benchmark:  https://chrsmrrs.github.io/datasets/docs/datasets/

You can find similar projects on this dataset: https://paperswithcode.com/sota/graph-classification-on-zinc

In [2]:
import torch
from torch_geometric.datasets import TUDataset
from torch_geometric.loader import DataLoader
import torch.nn.functional as F
from torch_geometric.nn import GCNConv, global_mean_pool, GATConv, GINConv, GINEConv
from torch.nn import Sequential, Linear, ReLU
from torch.optim.lr_scheduler import ReduceLROnPlateau

In [3]:
# Load ZINC datasets
dataset = TUDataset(root='./data', name='ZINC_train')

In [4]:
print(f"Example of a graph:\n {dataset[0]}\n")
print(f"Node features:\n {dataset.x}\n")
print(f"Edge features:\n {dataset.edge_attr}\n")
print(f"Graph labels:\n {dataset.y}")

Example of a graph:
 Data(edge_index=[2, 72], x=[33, 28], edge_attr=[72, 3], y=[1])

Node features:
 tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.]])

Edge features:
 tensor([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        ...,
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 1., 0.]])

Graph labels:
 tensor([ 3.0464,  0.4907,  1.0851,  ..., -1.8943,  2.3303,  1.8092])


# Hints
- you may need a dataloader since the dataset is very large
- you are free to proceed with any architecture, supervised / unsupervised / self-supervised
- you can find multiple examples of similar tasks or model on github